### ISSUE TITLE
Function interpolation and approximation

### ISSUE THREAD

**Issue by philsupertramp** [philsupertramp/game-math#30]
Another field of numerical mathematics is function interpolation and approximation.
Have a read here[1]

### TODO:
- [ ] base interpolation data structure
- [ ] evaluation methods
- [ ] representation in bases
- [ ] string representation of function in given base

- [1] https://wiki.godesteem.de/wiki/interpolation-and-approximation/
