### ISSUE TITLE
extend ds module

### ISSUE THREAD

**Issue by philsupertramp** [philsupertramp/game-math#61]
Implement several classic approaches such as
- [ ] classifiers:
   - [x] #69
   - [x] #70
   - [ ] #71
- [ ] #64
   - [ ] one-hot encoding
   - [ ] bag-of-words features
   - [ ] normalization
- [ ] #65
  - [x] PCA
  - [ ] **L**inear **D**iscriminate **A**nalysis 
- [ ] #68
   - [ ] image data
   - [ ] tabular data
   - [ ] text data
- [ ] #66
- [ ] #67
